# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/237/bin/cmake

# The command to remove a file.
RM = /snap/cmake/237/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adrian/Desktop/Studia/SemV/AAL/AAL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adrian/Desktop/Studia/SemV/AAL/AAL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/237/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/203/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adrian/Desktop/Studia/SemV/AAL/AAL/CMakeFiles /home/adrian/Desktop/Studia/SemV/AAL/AAL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adrian/Desktop/Studia/SemV/AAL/AAL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AAL

# Build rule for target.
AAL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AAL
.PHONY : AAL

# fast build rule for target.
AAL/fast:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/build
.PHONY : AAL/fast

src/data_structures/Graph.o: src/data_structures/Graph.cpp.o

.PHONY : src/data_structures/Graph.o

# target to build an object file
src/data_structures/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Graph.cpp.o
.PHONY : src/data_structures/Graph.cpp.o

src/data_structures/Graph.i: src/data_structures/Graph.cpp.i

.PHONY : src/data_structures/Graph.i

# target to preprocess a source file
src/data_structures/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Graph.cpp.i
.PHONY : src/data_structures/Graph.cpp.i

src/data_structures/Graph.s: src/data_structures/Graph.cpp.s

.PHONY : src/data_structures/Graph.s

# target to generate assembly for a file
src/data_structures/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Graph.cpp.s
.PHONY : src/data_structures/Graph.cpp.s

src/data_structures/Vertex.o: src/data_structures/Vertex.cpp.o

.PHONY : src/data_structures/Vertex.o

# target to build an object file
src/data_structures/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Vertex.cpp.o
.PHONY : src/data_structures/Vertex.cpp.o

src/data_structures/Vertex.i: src/data_structures/Vertex.cpp.i

.PHONY : src/data_structures/Vertex.i

# target to preprocess a source file
src/data_structures/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Vertex.cpp.i
.PHONY : src/data_structures/Vertex.cpp.i

src/data_structures/Vertex.s: src/data_structures/Vertex.cpp.s

.PHONY : src/data_structures/Vertex.s

# target to generate assembly for a file
src/data_structures/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/data_structures/Vertex.cpp.s
.PHONY : src/data_structures/Vertex.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mappers/StudentScheduleProblemMapper.o: src/mappers/StudentScheduleProblemMapper.cpp.o

.PHONY : src/mappers/StudentScheduleProblemMapper.o

# target to build an object file
src/mappers/StudentScheduleProblemMapper.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/mappers/StudentScheduleProblemMapper.cpp.o
.PHONY : src/mappers/StudentScheduleProblemMapper.cpp.o

src/mappers/StudentScheduleProblemMapper.i: src/mappers/StudentScheduleProblemMapper.cpp.i

.PHONY : src/mappers/StudentScheduleProblemMapper.i

# target to preprocess a source file
src/mappers/StudentScheduleProblemMapper.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/mappers/StudentScheduleProblemMapper.cpp.i
.PHONY : src/mappers/StudentScheduleProblemMapper.cpp.i

src/mappers/StudentScheduleProblemMapper.s: src/mappers/StudentScheduleProblemMapper.cpp.s

.PHONY : src/mappers/StudentScheduleProblemMapper.s

# target to generate assembly for a file
src/mappers/StudentScheduleProblemMapper.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/mappers/StudentScheduleProblemMapper.cpp.s
.PHONY : src/mappers/StudentScheduleProblemMapper.cpp.s

src/problem/StudentScheduleProblem.o: src/problem/StudentScheduleProblem.cpp.o

.PHONY : src/problem/StudentScheduleProblem.o

# target to build an object file
src/problem/StudentScheduleProblem.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/StudentScheduleProblem.cpp.o
.PHONY : src/problem/StudentScheduleProblem.cpp.o

src/problem/StudentScheduleProblem.i: src/problem/StudentScheduleProblem.cpp.i

.PHONY : src/problem/StudentScheduleProblem.i

# target to preprocess a source file
src/problem/StudentScheduleProblem.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/StudentScheduleProblem.cpp.i
.PHONY : src/problem/StudentScheduleProblem.cpp.i

src/problem/StudentScheduleProblem.s: src/problem/StudentScheduleProblem.cpp.s

.PHONY : src/problem/StudentScheduleProblem.s

# target to generate assembly for a file
src/problem/StudentScheduleProblem.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/StudentScheduleProblem.cpp.s
.PHONY : src/problem/StudentScheduleProblem.cpp.s

src/problem/generators/AcyclicGraphGenerator.o: src/problem/generators/AcyclicGraphGenerator.cpp.o

.PHONY : src/problem/generators/AcyclicGraphGenerator.o

# target to build an object file
src/problem/generators/AcyclicGraphGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/generators/AcyclicGraphGenerator.cpp.o
.PHONY : src/problem/generators/AcyclicGraphGenerator.cpp.o

src/problem/generators/AcyclicGraphGenerator.i: src/problem/generators/AcyclicGraphGenerator.cpp.i

.PHONY : src/problem/generators/AcyclicGraphGenerator.i

# target to preprocess a source file
src/problem/generators/AcyclicGraphGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/generators/AcyclicGraphGenerator.cpp.i
.PHONY : src/problem/generators/AcyclicGraphGenerator.cpp.i

src/problem/generators/AcyclicGraphGenerator.s: src/problem/generators/AcyclicGraphGenerator.cpp.s

.PHONY : src/problem/generators/AcyclicGraphGenerator.s

# target to generate assembly for a file
src/problem/generators/AcyclicGraphGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/generators/AcyclicGraphGenerator.cpp.s
.PHONY : src/problem/generators/AcyclicGraphGenerator.cpp.s

src/problem/solver/StudentScheduleSolver.o: src/problem/solver/StudentScheduleSolver.cpp.o

.PHONY : src/problem/solver/StudentScheduleSolver.o

# target to build an object file
src/problem/solver/StudentScheduleSolver.cpp.o:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/solver/StudentScheduleSolver.cpp.o
.PHONY : src/problem/solver/StudentScheduleSolver.cpp.o

src/problem/solver/StudentScheduleSolver.i: src/problem/solver/StudentScheduleSolver.cpp.i

.PHONY : src/problem/solver/StudentScheduleSolver.i

# target to preprocess a source file
src/problem/solver/StudentScheduleSolver.cpp.i:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/solver/StudentScheduleSolver.cpp.i
.PHONY : src/problem/solver/StudentScheduleSolver.cpp.i

src/problem/solver/StudentScheduleSolver.s: src/problem/solver/StudentScheduleSolver.cpp.s

.PHONY : src/problem/solver/StudentScheduleSolver.s

# target to generate assembly for a file
src/problem/solver/StudentScheduleSolver.cpp.s:
	$(MAKE) -f CMakeFiles/AAL.dir/build.make CMakeFiles/AAL.dir/src/problem/solver/StudentScheduleSolver.cpp.s
.PHONY : src/problem/solver/StudentScheduleSolver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AAL"
	@echo "... edit_cache"
	@echo "... src/data_structures/Graph.o"
	@echo "... src/data_structures/Graph.i"
	@echo "... src/data_structures/Graph.s"
	@echo "... src/data_structures/Vertex.o"
	@echo "... src/data_structures/Vertex.i"
	@echo "... src/data_structures/Vertex.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mappers/StudentScheduleProblemMapper.o"
	@echo "... src/mappers/StudentScheduleProblemMapper.i"
	@echo "... src/mappers/StudentScheduleProblemMapper.s"
	@echo "... src/problem/StudentScheduleProblem.o"
	@echo "... src/problem/StudentScheduleProblem.i"
	@echo "... src/problem/StudentScheduleProblem.s"
	@echo "... src/problem/generators/AcyclicGraphGenerator.o"
	@echo "... src/problem/generators/AcyclicGraphGenerator.i"
	@echo "... src/problem/generators/AcyclicGraphGenerator.s"
	@echo "... src/problem/solver/StudentScheduleSolver.o"
	@echo "... src/problem/solver/StudentScheduleSolver.i"
	@echo "... src/problem/solver/StudentScheduleSolver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

